Repository discoverygarden/dgi_migrate, pull requests merged in 2023-10, with the labels that each got.

#116 D10-9: Drop `drupal/migrate_tools:^6`
  composer.json
Labels: patch

#115 D10-9: Update to account for newer `migrate_tools`.
  composer.json
  drush.services.yml
  src/Drush/Commands/MigrateCommands.php
  src/Form/MigrationExecuteForm.php
  src/MigrateBatchExecutable.php
  src/StatusFilter.php
Labels: major

#112 UNRI2-152: Add very basic support for cardinality
  modules/dgi_migrate_foxml_standard_mods/migrations/dgis_nodes.yml
Labels: minor
